remote_theme: open-permaculture/just-the-docs

title: Open Permaculture

# Color scheme supports "light" (default), "dark" and "custom"
color_scheme: custom

logo: "/assets/images/open-permaculture-favicon.png"

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

aux_links:
  "Contribute":
    - "https://open-permaculture.com/contributing.html"

# External navigation links
nav_external_links:
  - title: Permaculture Forums
    url: https://permies.com/forums
    hide_icon: false # set to true to hide the external link icon - defaults to false
  - title: Permaculture Institute
    url: https://permaculture.org/
    hide_icon: false
  - title: Design Manual
    url: https://www.tagaripublications.com/
    hide_icon: false
